alias app='cd ~/../www/kubo421/laravel_project/laravel_project/app'
alias view='cd ~/../www/kubo421/laravel_project/laravel_project/resources/views'
alias model='cd ~/../www/kubo421/CakePHP/cakephp/app/Model'
alias cont='cd ~/../www/kubo421/laravel_project/laravel_project/app/Http/Controllers'
alias conf='cd ~/../www/kubo421/laravel_project/laravel_project/config'
alias mid='cd ~/../www/kubo421/laravel_project/laravel_project/app/Http/Middleware'
alias data='cd ~/../www/kubo421/laravel_project/laravel_project/database'
alias routes='cd ~/../www/kubo421/laravel_project/laravel_project/routes'
alias lara='cd ~/../www/kubo421/laravel_project/laravel_project'

